version: "3.7"
networks:
    premier:

services:
    nginx:
        image: nginx:latest
        working_dir: /var/www
        ports:
            - "80:80"
        volumes:
            - './public:/var/www/public'
            - './storage/app:/var/www/storage/app:cached'
            - './docker/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf'
        networks:
            - premier

    php-fpm:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                - UID=${UID-1000}
                - GID=${GID-1000}
        image: php-fpm-premier
        working_dir: /var/www
        volumes:
            - './:/var/www/'
            - './docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini'
        networks:
            - premier

    mysql:
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
        image: mysql-premier
        restart: always
        environment:
            MYSQL_DATABASE: premier
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./storage/db-data:/var/lib/mysql
        networks:
            - premier
